apiVersion: apps/v1
kind: Deployment
metadata:
  name:  influxdb
  labels:
    name:  influxdb
spec:
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 1
  #   type: RollingUpdate
  selector:
    matchLabels:
      name: influxdb
  template:
    metadata:
      labels:
        name:  influxdb
    spec:
      containers:
      - image:  influxdb:1.7-alpine
        name:  influxb
        resources:
        #   requests:
        #     cpu: "20m"
        #     memory: "55M"
          limits:
            cpu: "500m"
            memory: "128M"
        # livenessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 5000
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 5000
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
        env:
        - name:  INFLUXDB_DB
          value:  Monitor       
        - name:  INFLUXDB_USER
          value:  Monitor       
        - name:  INFLUXDB_PASSWORD
          value:  Secr3t       
        ports:
        - containerPort:  8086
          name:  http 
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: bdd

      volumes:
        - name: bdd
          hostPath:
            path: /Data/InfluxDB
            type: DirectoryOrCreate
      # restartPolicy: Always
      # imagePullPolicy: Always