apiVersion: v1
kind: Namespace
metadata:
  name:  test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-admin-user
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-admin
  namespace: test
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: test-admin
  namespace: test
subjects:
- kind: User
  name: test-admin-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: test-admin
  apiGroup: rbac.authorization.k8s.io
